### ISSUE TITLE
older bukkit support

### ISSUE THREAD

**Issue by madtomic** [Drepic26/CouponCodes3#10]
Please add support for 1.7.9

**Comment by Drepic26** [comment]
I have no intent of providing support for outdated versions. As you can see [here](http://mcstats.org/global/), many servers are already running 1.8. It's not worth my time to backtrack and provide support for an obsolete version which people should update from anyway.

If you would like to, fork the project from 9a8ebad and fix any compile errors there. There shouldn't be many changes in the api, so it should work anyway.

Otherwise, I strongly recommend you make the move to 1.8.1 on your server. [Spigot is available here.](http://www.spigotmc.org/)

**Comment by madtomic** [comment]
Thank you anyway. I will look for alternate plugin.
