### ISSUE TITLE
Add coupons to run console commands

### ISSUE THREAD

**Issue by madtomic** [Drepic26/CouponCodes3#3]
Could you please add the feature to use a console command upon redeeming a coupon?

**Comment by madtomic** [comment]
I understand and thank you. Perhaps custom set commands. ?

**Comment by madtomic** [comment]
The plugin I mention is an example . And I understand your concerns.

**Comment by Drepic26** [comment]
This still seems to be a widely requested feature, so I'm re-opening this for discussion and consideration. I would like to hear input from users however, pertaining to what type of commands they would use this for. In addition, please take this as an opportunity to voice any exploit/security concerns about running commands as console. 

It is entirely possible that instead of command coupons, it will be covered with more coupon types, depending on input here.

**Comment by madtomic** [comment]
What I envision is using this pluin and after the coupon code is redeemed it would execute a command (which is configurable via config.yml) 

Just another way this can be use to reward players and let player buy coupon codes.

The sample command I was referring to was..
/vip addvip <.Player> <.Group> <.Time>

I think it has to detect playername and group and time can be set.

http://dev.bukkit.org/bukkit-plugins/playervip/pages/commands-and-permissions/

This command would run either player or console.

What are your concerns to this?

**Comment by Drepic26** [comment]
@madtomic I don't want users to have to pre-specify commands in the config, if possible. That is too much of a hassle in my opinion. Any coupons added should be as others are, for example commands would be `/coupon add cmd <coupon name/random> <command> [usetimes] [time]`

As to detecting player name, I would use the same syntax as [minecraft's target variables](http://minecraft.gamepedia.com/Commands), for simplicity.

**Comment by Sunlost** [comment]
Here's an idea. When a player uses a command coupon, a staff member with the correct permission should have to approve the use of that coupon code for the player. This option would be toggleable in the config. All approvals would be logged in a file, including the player using the coupon, the player who approved the coupon, the command, and coupon name. It's the administrator's fault if the command coupon system is abused by players. 

Some commands I would want to use are PEX commands, and currency giving commands.

**Comment by Drepic26** [comment]
@Sunlost That works in theory, but in practice would become cumbersome for server admins, especially on larger severs. As to currency giving commands, if the currency plugin uses [Vault](http://dev.bukkit.org/bukkit-plugins/vault/), which all major ones do, then it can be done via the existing econ coupon.

I have had a recent rethinking however, and I do believe you are right when you say that it should be the administrators fault if the system in place is abused. What I am responsible for however is providing the means to prevent its abuse.

One idea I was tossing around was scrapping different coupon types entirely, and making coupons compound, that is, one coupon could be for multiple things. For example, a coupon for a cookie,  two diamonds and ten xp levels would look like `/coupon add item:cookie;1,diamond;2|xp:10`. This is similar to the format I have in place in my other plugin, [AmpleChatBot](http://dev.bukkit.org/bukkit-plugins/ample-chat-bot/), where the bot can respond with both text and running commands. My only concern with this is that commands would get too complicated, especially after completing #9.

Otherwise, here is a proposed list of coupon type prefixes for this system:

Prefix|Effect
---|---
item:|Gives the player items
xp:|Gives the player xp
econ:|Gives the player economy money(Not yet supported on Canary)
rank:|Sets the player to a certain rank(Requires Vault on Bukkit)
cmd:|Runs a command as console
pcmd:|Runs a command as player

**Comment by madtomic** [comment]
Seems interesting.

**Comment by Drepic26** [comment]
Just to put into a little perspective what I said about commands being too complicated if this is done, here's what it would look like if you wanted to create a coupon to give ten levels, 5$, and six enchanted birch planks named Fred with the lore "Delicious".

`/coupon add examplecoupon xp:10|econ:5|item:planks;6;1;{display:{Name:Fred},{Lore:["Delicious"]},{ench:[{id:16,lvl:2}]}}`

Note that this is a somewhat extreme example using minecraft's NBT tag format to add the enchantments and lore to the item, since I have not yet implemented enchants and lore I will most likely have devised an easier way of specifying

**Comment by Drepic26** [comment]
This is getting a little off topic, so I'm moving the discussion on this format to change to #18. This issue should remain for discussion of command coupons, which I have decided will be implemented.

**Comment by Sunlost** [comment]
@Drepic26 Thanks :)

Also, what I meant by currency, is token shop currencies. A command must be run to give said token currencies, as the token plugin isn't compatible with Vault.

**Comment by Sketaful** [comment]
How would commands be exploited if possible to make? A simple extra permission for who would be able to make coupons with commands should solve that, wouldn't it? 

I know I'd as an admin would love to offer coupons to my players with a command on it. But I wouldn't offer other players the permissions to make their own.

Wouldn't it also be easier if commands was made to use their commands as "server"? What I mean is that a command run as console should be run like if it had been written in the console. This way all plugins that support commands in the console should work as well, right? 
You could support wildcards like {player}.

**Comment by Drepic26** [comment]
@Sketaful My original thinking was that because commands would be run as console, this gives anyone with the pernission to add coupons the ability to run a command as console. I plan on adding separate perm nodes for coupons however, which is likely to look something like this
* cc.add.*
  * cc.add.item
  *cc.add.xp
  *cc.add.econ
  *cc.add.rank
  *cc.add.cmd

What also needs to be considered is how to handle it when I possibly make the changes discussed in #18

Also discussed there is how this format will work, and will allow for running commands as both console and/or player

**Comment by Sketaful** [comment]
I was thinking to ask for player/console. But then I figured that why? If a command is run as player it means they might just as well just type the command themself making the coupon quite useless, doesn't it?

**Comment by Drepic26** [comment]
@Sketaful Yes running a command as player on its own might seem useless, but makes sense if I implement compound coupons discussed in #18. If anything, it just gives server owners more flexibility to do what they want

**Comment by Sketaful** [comment]
Well, it's been a while so lets refresh my memories. A coupon isn't a physical thing. They still have to use /redeem <code> for it?

**Comment by Drepic26** [comment]
@Sketaful  Yes. An overview of commands and permissions can be found [here](http://drevelopment.com/couponcodes/)

**Comment by bclemmey** [comment]
Command coupons will basically open up anything I could ever want to do, and as long as adding a coupon allows me to reference the player redeeming the coupon (like having it run /give, but actually /give <player redeeming coupon> tnt 1 for example) then it'll work whether it is running as the player or the console. I use CommandHelper to script all sorts of simple chains of events that don't require a new plugin, and with this I can simply run one of my quick scripts to add any function I want to a coupon. Infinitely useful.

**Comment by Drepic26** [comment]
In order to keep the format of the add command as it is, <code>/coupon add cmd \<Coupon name/random> \<command> [use times] [time]</code>, and in the interests of keeping the <code>use times</code> and <code>time</code> parameters optional, what do you guys think about needing to enclose the command in quotes?
 I.E. </code>/coupon add cmd testcoupon "give %p cookie"</code>
As much as I would like to avoid this, I'm hard pressed to think of another way of doing it due to the variable nature of command lengths.

**Comment by bclemmey** [comment]
@Drepic26 That seems like the right way to go. It would retain the current format and allow any command to be added.

**Comment by Ponderavita** [comment]
This Feature is a Must have, the CMD feature.  Im somewhat new  at being a MC server admin, but many other plugins have this ability, GA Listener & MysteryCrates ( had a issue with people duping the crates in creative world, But i disabled them there).  There is even another coupon plugin thats uses this! and to me adding a permission  to create EACH TYPE OF code is good, 

The only dooms day thought i have though is like that Disgruntled  admin! In like bigger networks and stuff , but its also up to the server OWNER how he deploys it. but for my set up it seems perfect!

**Comment by NewBestX** [comment]
I can't see why the cmd feature is dangerous. A user with permissions could already create a cupon with the rank owner and redeem it himself, couldn't he? In my opinion, only the owner and some extremly trusted admins should have permission to create cupons. If the owner gives the permissions to many users, that's his fault.

For the quote problem, you could add two flags: -u for use times and -t for time. The command will look like that:
/coupon add cmd testcoupon give %p cookie
/coupon add cmd testcoupon give %p cookie -u:4
/coupon add cmd testcoupon give %p cookie -u:4 -t:12
OR with spaces instead of ":"
/coupon add cmd testcoupon give %p cookie -u 4
/coupon add cmd testcoupon give %p cookie -u 4 -t 12

This type of flags is used in Multiverse.
This is just an alternative to the quotes, but I think it would be easier using quotes...

In conclusion, I think this feature must be added as soon as possible :)

**Comment by Drepic26** [comment]
@NewBestX I did a bit of experimentation with quotes and it was a bit clunky (Being picky if you forgot the end quote and such), and I believe flags are a much better solution. I've already implemented the coupon, now I just need to complete the command handling and it will be good to go.

**Comment by Drepic26** [comment]
So after a little thinking and a _lot_ of testing, I've decided that the best and least intrusive way to do this would be to remove the use and time arguments completely, and add two other commands to set them.

For example,
<code>/coupon add item \<Coupon name/random> \<item1:amount,item2:amount,...> [use times] [time]</code>
would become
<code>/coupon add item \<Coupon name/random> \<item1:amount,item2:amount,...></code>

In addition, the following commands would be added
<code>/coupon time \<Coupon name> \<time> </code>
<code>/coupon uses \<Coupon name> \<uses> </code>

I think this is the most non-intrusive way to do it as well as the cleanest solution. What do you guys think?

**Comment by madtomic** [comment]
Thank you!
